### ISSUE TITLE
Error at the end of a matplotlib plot using ipe backend

### ISSUE THREAD

**Issue by tianyikillua** [otfried/ipe-tools#1]
First of all what a wonderful tool you've developped! All my future figures will be plotted using your backend which can be more easily edited in ipe and integrated into my LaTeX document.

In some cases I encounter this error message at the end of the plotting (after the generation of `.ipe` files, so in fact harmless)

```
Exception TypeError: "'NoneType' object is not callable" in <bound method LatexManager.__del__ of <matplotlib.backends.backend_pgf.LatexManager instance at 0x7feb705631b8>> ignored
```

and I couldn't find out why...

**Comment by michK** [comment]
Hi Otfriet

When I try to use the backend I get:
'''
Traceback (most recent call last):
  File "historical_FR.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\User\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 10
9, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "C:\Users\User\Anaconda3\lib\site-packages\matplotlib\backends\__init__.p
y", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Users\User\Dropbox\Meesters\Historical FR\backend_ipe.py", line 4
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
'''

**Comment by otfried** [comment]
Have a look at the file backend_ipe.py.  It seems you save it incorrectly, and it contains HTML, not Python code.

This link will give you the actual Python script:

https://raw.githubusercontent.com/otfried/ipe-tools/master/matplotlib/backend_ipe.py

**Comment by michK** [comment]
Thank you, I litterally just saw that that was what happened. I cloned the whole project now and got the right file. However, now I still get an error:

	Traceback (most recent call last):
	  File "historical_FR.py", line 4, in <module>
		import matplotlib.pyplot as plt
	  File "C:\Users\User\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 10
	9, in <module>
		_backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

	  File "C:\Users\User\Anaconda3\lib\site-packages\matplotlib\backends\__init__.p
	y", line 32, in pylab_setup
		globals(),locals(),[backend_name],0)
	  File "C:\Users\User\Dropbox\Meesters\Historical FR\backend_ipe.py", line 48
		rcParams.validate['ipe.preamble'] = lambda (s) : s
												   ^
	SyntaxError: invalid syntax

**Comment by otfried** [comment]
You are using Python 3.   The backend was written for Python 2.  I should fix that at some point, but I never had a need to use Python 3 yet.

**Comment by michK** [comment]
Ahh I see.

Thank you very much!

Cheers!
