### ISSUE TITLE
Cannot install pdftoipe on MAC OSX EL CAPITAN

### ISSUE THREAD

**Issue by cesareolivera** [otfried/ipe-tools#10]
Can you explain the installation instructions please.

regards!

**Comment by otfried** [comment]
Compiling pdftoipe itself is easy - just say "make" - but you'll need to have the poppler library installed.  I cannot help you with that (it has many dependencies, e.g. fontconfig).   The easiest would be to use macports, where you can install either poppler (and then compile yourself), or you can directy install the ipe-tools package which contains pdftoipe.
