### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by clutsko** [otfried/ipe-tools#11]
I have a graph saved as a .pdf. Anytime I run pdftoipe on the pdf this generates an .ipe file which I then try to open with IPE, only to recieve the following error:

document "file.ipe" could not be opened

Parsing error at position 210

when I open the .ipe file there is no clear position 210, only a giant string of hex.

**Comment by otfried** [comment]
pdftoipe doesn't always work - there's no guarantees.  As the documentation says, "it tries..."

If you want me to look at this you'd have to attach the pdf file or a link to it.

**Comment by clutsko** [comment]
Many thanks. Here is the pdf file.

**Comment by otfried** [comment]
Attaching by email doesn't seem to work - you'll have to visit the github site and drag the file into a comment.

**Comment by clutsko** [comment]
[gamma-n-vs-param.pdf](https://github.com/otfried/ipe-tools/files/364755/gamma-n-vs-param.pdf)

Apologies

**Comment by otfried** [comment]
I tried it with pdftoipe version 2014/03/03, and it works just fine.

Here is the converted version:

[gamma-n-vs-param-converted.zip](https://github.com/otfried/ipe-tools/files/364764/gamma-n-vs-param-converted.zip)

**Comment by clutsko** [comment]
I see. Many thanks. I was using an older version of ipe.
