### ISSUE TITLE
ipe does not find the pdf embedded in the ipe file generated by annotate.py

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe-tools#15]
Ipe 7.2.6 with configuration
```
* Latex program path: 
* Latex directory: ~/.ipe/latexrun/
```
When opening a .ipe file generated by annotate.py, Ipe does not find the pdf file.
Copying the pdf to ~/.ipe/latexrun fixes the issue.

**Comment by otfried** [comment]
Starting with Ipe 7.2.13, the directory containing the Ipe document is added to TEXINPUTS when running Latex.
