### ISSUE TITLE
Inconsistent Arrowtip handling

### ISSUE THREAD

**Issue by derlunz** [otfried/ipe-tools#18]
Hi,
while working on svgto ipe I've created an ipe file, [last-arrow-missing.ipe](https://gist.github.com/derlunz/356f4d683d705250d52bbb6e25f1281a)

It contains 3 paths with arrow tips. The last path doesn't show the arrows.
Can you tell why this happens with current ipe 7.2.6?
The file uses the 'old' format, could that be the issue?

**Comment by otfried** [comment]
Replace `arror` and `rarror` by `arrow` and `rarrow` and that will work :-)
