### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by bnyasd** [otfried/ipe-tools#22]
I had produced an ipe file a year ago and now I cannot open the file. I realized that, the producer of the file was changed to Mac OS X 10.10.1 Quartz PDFContext. And as you mentioned in one of your comments, the file is probably not recoverable anymore. Then, I have tried to use pdftoipe, however, when I wanna open the ipe file, I receive a parsing error. Could you please kindly help me with the issue. I have attached the file here:
[0.pdf](https://github.com/otfried/ipe-tools/files/757599/0.pdf)

Bests,

**Comment by otfried** [comment]
Have a look here:

https://github.com/otfried/ipe-wiki/wiki/FAQ#when-ipe-refuses-to-open-a-pdf-file-you-created-with-ipe
