### ISSUE TITLE
How to run figtoipe

### ISSUE THREAD

**Issue by harvanek** [otfried/ipe-tools#33]
How to run figtoipe on mac os (10.14.2)? After compiling a copy executable file to ipe app (Macintosh HD⁩ ▸ ⁨Applications⁩ ▸ ⁨Ipe⁩ ▸ ⁨Contents⁩) it doesn't working. I also tried run figtoipe from terminal. What is the right procedure? Thank you and sorry for stupid question (I am only user).

**Comment by otfried** [comment]
Open a terminal and say:
```
git clone https://github.com/otfried/ipe-tools.git
cd ipe-tools/figtoipe
make
```
This will create `figtoipe` in the current directory.  Run it by saying
```
./figtoipe
```
