### ISSUE TITLE
Error about `GooString` when compiling pdftoipe

### ISSUE THREAD

**Issue by miguelgarces123** [otfried/ipe-tools#39]
I can't find a way to install the package in Centos 7, is it possible to do it?

I have this error when trying from a centos 7 server:

![image](https://user-images.githubusercontent.com/41314268/68350324-efd17a00-00cd-11ea-8809-aaf06a71c5ce.png)

**Comment by otfried** [comment]
poppler changed dramatically at some point, replacing their own type GooString by C++'s std::string.

The master branch of ipe-tools needs poppler v0.73 or something like that.   Obviously your version of poppler is older than that, so you need to checkout the branch `old-poppler`.  (It will work with Poppler version v0.68.)

So you can say;
```
git clone https://github.com/otfried/ipe-tools.git
cd ipe-tools
git checkout old-poppler
cd pdftoipe
make
```
