### ISSUE TITLE
pdftoipe: texts are not included in generated xml file

### ISSUE THREAD

**Issue by budinero** [otfried/ipe-tools#47]
Hi, I am using the debian versions of pdftoipe. When using 7.2.20 (I do not know if it corresponds with the last git version), no text is included in the generated xml file. When using an older version, 7.2.7.2, all texts are included as expected, depending on the selected options. I am testing it with pdf files obtained from MATLAB plots.

**Comment by otfried** [comment]
Can you attach an input file and the exact command line you are using to run pdftoipe?

**Comment by otfried** [comment]
And what is the version output by  saying just `pdftoipe`?

**Comment by budinero** [comment]
Command (in both cases):
`pdftoipe example.pdf example.ipe `

Newer pdftoipe (deban version 1:7.2.20-1+b1):  pdftoipe version 2019/12/10
Older pdftoipe (debian version 1:7.2.7.2-1+b1): pdftoipe version 2018/11/01

Attached:
[example.pdf](https://github.com/otfried/ipe-tools/files/5195368/example.pdf) input file.
[example_older.txt](https://github.com/otfried/ipe-tools/files/5195371/example_older.txt) generated with version 2018/11/01
[example_newer.txt](https://github.com/otfried/ipe-tools/files/5195372/example_newer.txt) generated with version 2019/12/10

(I changed extensions from .ipe to .txt to upload ipe files)

**Comment by otfried** [comment]
It turns out that poppler has again changed the signature of some virtual functions, causing the functions in pdftoipe's output device to not be called.   Fixed the functions and added `override`, so in the future we will catch such problems at compile time.

**Comment by budinero** [comment]
Wow, compiled, tested and working. Thanks!
