### ISSUE TITLE
Cut a release tag

### ISSUE THREAD

**Issue by DomT4** [otfried/ipe-tools#5]
The old `tools` directory on the SF page seems to have been removed once the tools were moved here. Could you possibly cut a new tag here so we can [continue](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pdftoipe.rb) to package `pdftoipe`? Thanks!

**Comment by otfried** [comment]
I don't see why I need to mark any specific version as a release.  

As the packager, you can decide from the changelog if and when you want
to make a new package release.

**Comment by DomT4** [comment]
Because we package releases and only patch back urgent/security/etc fixes when necessary - We don't have the resources or server space to maintain 3000+ packages and update, upload and handle source-code tweaks for. That sort of thing is more common amongst Debian et al. but they have both a huge team and fairly unlimited server space.

The idea is that instead of:

```
download and install poppler
git clone https://github.com/otfried/ipe-tools.git
cd ipe-tools/pdftoipe
make
mv pdftoipe /usr/local/bin
```

The user can just do `brew install pdftoipe` and be done in a few seconds.

**Comment by otfried** [comment]
I thought homebrew just provides a recipe, so when the user types "brew
install pdftoipe", it would download the sources and compile it.   If
that is correct, your recipe can simply refer to the current git
version.

If you insist on using a specific commit, I guess you can just use the
commit id.

Cheers,
  Otfried

**Comment by DomT4** [comment]
We do, but that recipe uses an upstream tarball, or git tag, along with a `sha256` checksum or a `revision` which acts a checksum. You can see the [current](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pdftoipe.rb) formula, which is outdated compared to current syntax and checksum requirements, but the URL it is pointing at has been pulled off the server.

**Comment by otfried** [comment]
It seems that Homebrew supports head-only git repositories:

https://github.com/Homebrew/homebrew-head-only

figtoipe is already there, so it makes sense that pdftoipe goes there as
well.

**Comment by otfried** [comment]
In case you haven't seen my comment on homebrew/homebrew-head-only, I have now tagged today's state as release v7.2.6 (matching the current Ipe release).

**Comment by bfontaine** [comment]
Thank you @otfried!
