### ISSUE TITLE
svgtoipe for gradients

### ISSUE THREAD

**Issue by JosjaVanBever** [otfried/ipe-tools#63]
At https://otfried.github.io/ipe/70_presentations.html#gradient-patterns it is advised to use inkscape to create a gradient and than convert it to ipe using svgtoipe.py. However, after converting the svg below, the gradient is gone. (Note: the original svg has an intendation of 3 spaces per tab instead of 4 spaces per tab).

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    

    <svg
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:cc="http://creativecommons.org/ns#"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:svg="http://www.w3.org/2000/svg"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
        xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
        width="210mm"
        height="297mm"
        viewBox="0 0 210 297"
        version="1.1"
        id="svg8"
        inkscape:version="0.92.5 (2060ec1f9f, 2020-04-08)"
        sodipodi:docname="gradient.svg">
      <defs
          id="defs2">
         <linearGradient
             inkscape:collect="always"
             id="linearGradient855">
            <stop
                style="stop-color:#fc8a03;stop-opacity:1;"
                offset="0"
                id="stop851" />
            <stop
                id="stop859"
                offset="0.65925938"
                style="stop-color:#fc8a03;stop-opacity:0.51764706;" />
            <stop
                style="stop-color:#fc8a03;stop-opacity:0;"
                offset="1"
                id="stop853" />
         </linearGradient>
         <linearGradient
             inkscape:collect="always"
             id="linearGradient829">
            <stop
                style="stop-color:#efb806;stop-opacity:1"
                offset="0"
                id="stop825" />
            <stop
                id="stop833"
                offset="0.65157384"
                style="stop-color:#44ef06;stop-opacity:0.44705883" />
            <stop
                style="stop-color:#efbf06;stop-opacity:0;"
                offset="1"
                id="stop827" />
         </linearGradient>
         <radialGradient
             inkscape:collect="always"
             xlink:href="#linearGradient829"
             id="radialGradient835"
             cx="104.32143"
             cy="130.69048"
             fx="104.32143"
             fy="130.69048"
             r="45.357143"
             gradientUnits="userSpaceOnUse"
             gradientTransform="matrix(0.98333342,0,0,1,1.7386816,0)" />
         <radialGradient
             inkscape:collect="always"
             xlink:href="#linearGradient855"
             id="radialGradient857"
             cx="110.74702"
             cy="151.85713"
             fx="110.74702"
             fy="151.85713"
             r="51.026787"
             gradientTransform="matrix(1,0,0,0.99259261,0,1.1248655)"
             gradientUnits="userSpaceOnUse" />
      </defs>
      <sodipodi:namedview
          id="base"
          pagecolor="#ffffff"
          bordercolor="#666666"
          borderopacity="1.0"
          inkscape:pageopacity="0.0"
          inkscape:pageshadow="2"
          inkscape:zoom="0.35"
          inkscape:cx="-101.42857"
          inkscape:cy="548.57143"
          inkscape:document-units="mm"
          inkscape:current-layer="layer1"
          showgrid="false"
          inkscape:window-width="1848"
          inkscape:window-height="1016"
          inkscape:window-x="1992"
          inkscape:window-y="27"
          inkscape:window-maximized="1" />
      <metadata
          id="metadata5">
         <rdf:RDF>
            <cc:Work
                rdf:about="">
              <dc:format>image/svg+xml</dc:format>
              <dc:type
                  rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
              <dc:title></dc:title>
            </cc:Work>
         </rdf:RDF>
      </metadata>
      <g
          inkscape:label="Layer 1"
          inkscape:groupmode="layer"
          id="layer1">
         <ellipse
             style="opacity:1;fill:url(#radialGradient857);fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:0.79374999;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1"
             id="path849"
             cx="110.74702"
             cy="151.85713"
             rx="51.026787"
             ry="50.648811" />
      </g>
    </svg>

![gradient](https://github.com/otfried/ipe-tools/assets/33280928/65e72d46-9d49-4dd4-9d21-a0bb74c38dd1)

**Comment by otfried** [comment]
Ipe only implements gradients that vary between different colors.
Your gradient doesn't actually change the color, it varies between transparent and fully opaque.  This is not implemented in Ipe (yet).
If you change your gradient so that instead of interpolating between fully transparent and fully opaque orange, it interpolates between white and orange, you would get something that works in Ipe.   Of course you can then only use this on a white background...
