### ISSUE TITLE
ipe - matplotlib - sage

### ISSUE THREAD

**Issue by Etn40ff** [otfried/ipe-tools#7]
Some time ago I wrote a patch to export graphics from sage to ipe. It is
basically a wrapper for your matplotlib backend.
http://trac.sagemath.org/ticket/19667

During review it was pointed out that it would be better if it were implemented directly
upstream. I posted a comment at matplotlib on the topic:

https://github.com/matplotlib/matplotlib/issues/5630

Which in turn asked for your contribution.

**Comment by otfried** [comment]
I've followed up on your matplotlib issue, without any response so far.  I'd be happy to have the backend be merged into matplotlib, but until this happens I will need to keep the standalone version around.

**Comment by Etn40ff** [comment]
That long silence was kind of weird, let me see if I can ping people at matplotlib. 
In the mean time thank you
