### ISSUE TITLE
make matplotlib backend support python3

### ISSUE THREAD

**Issue by liubenyuan** [otfried/ipe-tools#8]
Hi, currently the matplotlib backend do not support python3, is there any plan of making it work on python3?

**Comment by otfried** [comment]
I certainly plan to do that at some point, but first I need to learn how to use the compatibility layer (so that the same code works on Python 2 and 3).  I can't give you any date when this will happen - if you need it quickly, you'll have to do it yourself.

**Comment by liubenyuan** [comment]
Thanks @otfried , I will try to fix it
